colorScheme = "slate"

defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

mainSections = ["services"]

[author]
name = "Strawberry Gecko Ltd"
image = "logo.svg"
headline = "Infrastructure • Security • Automation"

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = false

[homepage]
layout = "background"

[homepage.home]
enabled = true

[homepage.showRecent]
enabled = false
